### ISSUE TITLE
Teams Can't Be Found (Heroku)

### ISSUE THREAD

**Issue by hypersonicstormm** [pmariglia/showdown#100]
When I add a new team into the gen8 folder and config it to the file (the image may not be full but for me it's gen8/custom/pads_shifu), It for some reason can't find it and the logs say this:
![image](https://user-images.githubusercontent.com/87400978/151490865-30b586bb-205f-46a0-86c1-532c1867a89e.png)

![image](https://user-images.githubusercontent.com/87400978/151490807-a37a313b-de8a-4c33-9649-e5e9c104b36a.png)

any help would be appreaciated.

**Comment by pmariglia** [comment]
Huh, I actually can't even create an app on Heroku because of #99.

The app must've been flagged as violating their policies somehow. I may consider just removing the Heroku deploy altogether - I don't really maintain it anyways.

**Comment by hypersonicstormm** [comment]
Yea possibly just a heroku issue. The other preset teams work tho... crazy weird.
