### ISSUE TITLE
help

### ISSUE THREAD

**Issue by realpritam** [pmariglia/showdown#128]
![image](https://user-images.githubusercontent.com/105146731/193010879-52364447-07b5-410d-bd16-de8b2367d6ad.png)

**Comment by hsahovic** [comment]
This looks like an issue caused by python 3.10 - can you try using 3.9?

**Comment by pmariglia** [comment]
Yeah I haven't changed some of the concurrency code to be compatible with python 3.10 yet. You'll have to use Python 3.6-3.9

**Comment by realpritam** [comment]
so should how to install python 3.9 and uninstall 3.10?

**Comment by MattiasHenders** [comment]
I fixed this by running
`pip install --upgrade websockets`

**Comment by pmariglia** [comment]
Yeah turns out this was an issue with `websockets`, thanks @MattiasHenders.

Fixed in 70511b89b12c36625a6a40ac0938c4e0194ea283
