### ISSUE TITLE
Problem with gen3ou

### ISSUE THREAD

**Issue by jonasrhee1208** [pmariglia/showdown#136]
This error keeps popping up:
<img width="1715" alt="error" src="https://user-images.githubusercontent.com/68918408/204944212-391eecbf-f547-412b-936b-63ee512c8785.PNG">
and i have confirmed that the .env file has the team and the team is in the directory, what do i do?
(this is docker)

**Comment by jonasrhee1208** [comment]
WEBSOCKET_URI=sim.smogon.com:8000
PS_USERNAME=nope
PS_PASSWORD=nope
BOT_MODE=SEARCH_LADDER
POKEMON_MODE=gen3ou
TEAM_NAME:gen3/ou/beatup
RUN_COUNT=99999999999999999999999999999999999999999999999999999999999999999999999999999999999

**Comment by pmariglia** [comment]
@jonasrhee1208 

Change this:
```
TEAM_NAME:gen3/ou/beatup
```

To this:
```
TEAM_NAME=gen3/ou/beatup
```

Also make sure you've re-built the docker image after making changes to the contents of `gen3/ou/beatup`

**Comment by jonasrhee1208** [comment]
thx

**Comment by jonasrhee1208** [comment]
thx
