### ISSUE TITLE
Ai never uses perish song

### ISSUE THREAD

**Issue by jonasrhee1208** [pmariglia/showdown#137]
im running perish trap gengar but it is spamming mean look

**Comment by pmariglia** [comment]
Certain moves/interactions are not implemented in the engine and Perish Song is one of them. Implementing the logic for the bot to account for this is possible, but one of the many shortcomings of a search-based bot that can only see 2 turns ahead is that it wouldn't (without some help) be able to see the benefit of using such a move.
