### ISSUE TITLE
Ai dosent understand toxic

### ISSUE THREAD

**Issue by jonasrhee1208** [pmariglia/showdown#138]
When it got toxicd, it never switched

**Comment by pmariglia** [comment]
The bot definitely understands toxic - it is implemented as a side-condition that increments every turn and decrements HP accordingly.

[First turn toxic instructions](https://github.com/pmariglia/showdown/blob/89d8fac9361dda93f98e578c22d6ab6903eb1e16/tests/test_battle_mechanics.py#L3861) and [second turn toxic instructions](https://github.com/pmariglia/showdown/blob/89d8fac9361dda93f98e578c22d6ab6903eb1e16/tests/test_battle_mechanics.py#L3884)

The bot being bad is not evidence of it not understanding something.

**Comment by pmariglia** [comment]
going to close this. If you have evidence of the bot not understanding toxic besides it not switching, please feel free to re-open.
