### ISSUE TITLE
Is there a way to use just the battlebots?

### ISSUE THREAD

**Issue by Greeny127** [pmariglia/showdown#164]
First off - This is such a cool project 😄

Anyway. I wanted to be able to use just the battle bots. Like, instead of getting the data from Showdown and etc, I could feed in the data (pokemons available, items, moves, etc) directly to the battle bot and send out just the best move. Then update with the next part of the battle. In simple words, replace the showdown client with my own offline client

Is this possible, and if so, is it easy enough to single it out of the whole program?

Either way, Thank you! Again, this is just so cool xD

**Comment by pmariglia** [comment]
A bit tricky, but possible. You'd need to initialize a BattleBot, and then set various properties of the battle manually.

The annoying part is that I wrote a lot of this code with the assumption that you'll be connected to PokemonShowdown and will be updating the Battle properties from the data that comes back from the websocket. 

I've thought about refactoring the code so that it has a cleaner API so you can do things like you want, I just haven't had the motivation or the time.

Here is some code that seems to get you started:
```python
import data
from config import ShowdownConfig
from data.helpers import get_standard_battle_sets
from showdown.battle_bots.safest.main import BattleBot
from showdown.battle import Pokemon, Move

# required for some flags to be set
ShowdownConfig.configure()


def set_smogon_stats(list_of_pokemon_in_this_battle, pokemon_battle_type):
    smogon_usage_data = get_standard_battle_sets(
        pokemon_battle_type,
        pokemon_names=list_of_pokemon_in_this_battle
    )
    data.pokemon_sets = smogon_usage_data
    for pkmn, values in smogon_usage_data.items():
        data.effectiveness[pkmn] = values["effectiveness"]


def create_pkmn(name, level, moves):
    pkmn = Pokemon(name, level)

    pkmn.index = name  # this value normally exists for communicating with PS

    pkmn.moves = [Move(m) for m in moves]
    return pkmn


# call this if you want more intelligent set inferral.
# try to only call this once as it requires a rather costly query to the smogon stats page

# set_smogon_stats(["charizard", "venusaur", "blastoise"], "gen8ou")


battle_bot = BattleBot(None)
battle_bot.generation = "gen8"
battle_bot.user.active = create_pkmn("charizard", 100, ["flamethrower", "fly", "tackle", "dragonrage"])

battle_bot.user.reserve = [
    create_pkmn("venusaur", 100, ["leechseed", "dig", "tackle", "razorleaf"]),
    create_pkmn("blastoise", 100, ["surf", "shellsmash", "tackle", "coil"]),
]
battle_bot.opponent.active = create_pkmn("charizard", 100, ["flamethrower", "fly", "tackle", "dragonrage"])
battle_bot.opponent.reserve = [
    create_pkmn("venusaur", 100, ["leechseed", "dig", "tackle", "razorleaf"]),
    create_pkmn("blastoise", 100, ["surf", "shellsmash", "tackle", "coil"]),
]


best_move = battle_bot.find_best_move()[0][1:]

print(best_move)

```

Bear in mind I hacked this together in maybe 10 minutes so I can't guarantee this won't crash somewhere or be as strong as the regular code.

**Comment by Greeny127** [comment]
Right, I figured this would be a bit difficult as I tried delving into the code myself and it was written very tight with showdown. I did cut out bits and pieces but was somewhat unsuccessful but this looks like a good starting point, I'll give it a try and report back if I'm successful. Thanks 😁

**Comment by Greeny127** [comment]
I'm getting somewhat there, one glaring issue is that `updatebattle` function is just written completely with showdowns requests, and the fact that the bot randomly pulls moves that aren't in the active pokemon's moveset. I'll probably try for a bit more but I doubt I can do this myself so I'll close this and hopefully someone in the future does solve this :)

**Comment by Intenzi** [comment]
Has there been any traction by chance? I too am looking forward to being able to utilize it in an offline client setting, as long as its possible to separate the battling bot from ps it'd be pretty good.
Any suggestions towards the same?
