### ISSUE TITLE
How to get about stat in battle?

### ISSUE THREAD

**Issue by KlausRyu** [pmariglia/showdown#165]
Hello, I want to ask about if I want to get the Pokemon stat(still have how many HP,etc) in battle, how can i get or print it out?

**Comment by pmariglia** [comment]
Assuming you are using the [`safest` battle bot](https://github.com/pmariglia/showdown/blob/master/showdown/battle_bots/safest/main.py)

You can add debug logs right in the `find_best_move()` function.

This is the [Battle](https://github.com/pmariglia/showdown/blob/c4ade1697348893cea7dfab3201d01871c791462/showdown/battle.py#L58) object that is being inherited by the BattleBot. Using a debugger to stop execution in that function could also help.

**Comment by klauswonder** [comment]
hello there, can I ask about how I can get about what Pokemon I have, and what pokemon the opponent have.

I'm using random mode battle, and safest battle bot.

I was got about the pokemon battle stat and i print it out in config.py. I cant get any info about what 6Pokemon I using in the  debug log.
