### ISSUE TITLE
Disable Dynamax/Terastallization?

### ISSUE THREAD

**Issue by Pixeluchiha** [pmariglia/showdown#169]
Hello! I was just wondering if it is possible to disable the ability to Dynamax or Terastallize. I want to test teams in the AG format, but don't want them to be influenced by those gimmicks, especially since the bot is not programmed to know how to use them properly.

**Comment by pmariglia** [comment]
Building in a setting to do this would require some effort, however for your own testing you can remove/comment-out the following lines to stop the bot from dynamaxing and terastallizing:

[dynamax](https://github.com/pmariglia/showdown/blob/c4ade1697348893cea7dfab3201d01871c791462/showdown/battle_bots/helpers.py#L35-L36)

[terrastallize](https://github.com/pmariglia/showdown/blob/c4ade1697348893cea7dfab3201d01871c791462/showdown/battle_bots/helpers.py#L39-L40)

**Comment by Pixeluchiha** [comment]
> Building in a setting to do this would require some effort, however for your own testing you can remove/comment-out the following lines to stop the bot from dynamaxing and terastallizing:
> 
> [dynamax](https://github.com/pmariglia/showdown/blob/c4ade1697348893cea7dfab3201d01871c791462/showdown/battle_bots/helpers.py#L35-L36)
> 
> [terrastallize](https://github.com/pmariglia/showdown/blob/c4ade1697348893cea7dfab3201d01871c791462/showdown/battle_bots/helpers.py#L39-L40)

It looks like this worked, thank you!
