### ISSUE TITLE
Can't Find Saved Replays

### ISSUE THREAD

**Issue by Pixeluchiha** [pmariglia/showdown#171]
Hopefully last issue from me. I have the SAVE_REPLAY setting on "True", but it doesn't seem to be saving replay. I don't know if it makes a folder somewhere, or if they are saved online, but I have not been able to find replays and have just been saving them manually. If there is something I'm missing, I would appreciate it a lot if I could save the replays automatically instead of doing it myself.

**Comment by pmariglia** [comment]
Search here for your replay by username.

https://replay.pokemonshowdown.com/

The bot should also spit out some logs of the replay being saved after the battle finishes

**Comment by pmariglia** [comment]
To clarify: The replays are not saved locally by the bot, but are saved using PokemonShowdown's replay system.

**Comment by Pixeluchiha** [comment]
Oh wow, never knew this existed. Thanks!
