### ISSUE TITLE
I can't get it to challenge a user.

### ISSUE THREAD

**Issue by gotex007** [pmariglia/showdown#173]
I was able to get it to send a direct challenge (I won too). It did search_ladder and battled just fine using gen7randombattle. I tried using gen7randombattle too for the challenge_user but I'm not receiving the challenge in my internet browser window. I also don't know how, if it's possible, to open two PS clients so I can AI vs AI battle.

![GVyzyix](https://github.com/pmariglia/showdown/assets/8534139/9c3b3062-bc4f-4897-9821-280e6d71d993)

I'm really new to any of this. It's the first time I've successfully got a python program to run at all.

**Comment by gotex007** [comment]
Well today it won't even let me search_ladder gen7randombattle so I don't even know anymore. The terminal just closes after a few seconds.

**Comment by pmariglia** [comment]
Could you share some of the logs that the bot is printing out?

I have no issues challenging another user or playing battles on the ladder

**Comment by gotex007** [comment]
I don't know how I could have done that because I don't remember seeing logs anywhere but I've already since gotten rid of python, Pokemon Showdown, git, and this application since I couldn't figure out how to have two instances of the Pokemon Showdown client anyway and I had wanted to do AI vs AI battles.
