### ISSUE TITLE
Separate out the engine into an installable library

### ISSUE THREAD

**Issue by SirSkaro** [pmariglia/showdown#186]
There are a lack of battle simulators that are capable of performing search. Your agent is the only one I'm aware of that has a decent battle engine to perform search. I'm create my own agent that uses search but using `poke-env` to communicate with Pokemon Showdown.

I think it would be beneficial to separate out your engine into a stand-alone, installable library. I've actually proved this out already on [my fork](https://github.com/SirSkaro/poke-engine), and am using it in [my agent](https://github.com/SirSkaro/battle-master). Your `showdown` application would then use this installable library.

I did as much "lift-and-shift" as I could, changing as little as possible and keeping tests passing but removing everything pertaining to running as a stand-alone application. To me it would also makes sense to have separate projects for the `data` and `team` modules so that they can be loosely coupled and versioned independently. I realize there would have to be bigger refactors than what I did. Would love to hear your thoughts.

**Comment by pmariglia** [comment]
Love it. This is something I've wanted to do but just never had the time or motivation. I've kept everything in the `engine` (well, maybe besides `constants.py`) separate for this reason. Very glad to see that you were able to make it work.

When I get a chance I'll take a look at your fork and see if I could add my own setup.py in the `engine` folder, and perhaps publish it to pypi - a couple of other people have privately mentioned to me that they would be interested in this as well.

**Comment by SirSkaro** [comment]
Depending on how hard you want to go with creating a battle engine, you may want to take a look at the [engine](https://github.com/pkmn/engine) from the [pkmn project.](https://pkmn.cc/). I haven't looked too much into it, but it looks like a framework for building performant simulators. Perhaps this could help eek out a level or two in the search tree. Looks like someone has already made a [Python library](https://github.com/AnnikaCodes/PyKMN?tab=readme-ov-file) using this as a base, though I haven't looked too much into it either.

If I haven't disclaimed enough already, I know little to nothing about the pkmn project. I just found it interesting from a glance.

I learned about it from https://pkmn.ai/projects/#0ERROR

**Comment by SirSkaro** [comment]
Hi @scheibo - thank you very much for chipping in and for the correct. Your description and explanation was incredibly helpful - I had not looked into your project enough to realize it currently only targets gen 1. I also take it that you're a maintainer of [https://pkmn.ai](https://pkmn.ai). Thank you for putting that together, it's already been helpful for my current research project. 

I'm excited to see how the pkmn engine developer. But it sounds like it's probably not the direction this engine wants to take.

**Comment by pmariglia** [comment]
I ended up re-writing the entire engine part of this project in Rust: https://github.com/pmariglia/poke-engine.

Eventually, I'll be integrating the usage of that engine into this project and at that point I'll likely be deleting/archiving the python engine which is at this point inferior both in terms of features and performance.

I assume the rust engine will be appropriate for your use-case but if you still desire the python engine I'd suggest forking it and creating a standalone installable library with it.

**Comment by SirSkaro** [comment]
Awesome work! I'm excited to see your engine get revamped into an even more efficient form. Can't wait to see it be used to tear up the ladder ;)
