### ISSUE TITLE
bot cant connect to showdown

### ISSUE THREAD

**Issue by mancho2000** [pmariglia/showdown#193]
Hi,

I tried to run a bot that I last used 5-6 months ago and got the following error:

TimeoutError: [Errno 10060] Connect call failed ('15.235.87.127', 8000)

How could I fix this?

**Comment by dracnelking** [comment]
I have the same problem, I tried connecting the bot today and it doesn't work, a month ago it worked correctly.

I think the problem is WEBSOCKET_URI=sim.smogon.com:8000, the address is not correct or they changed it.

Let's see if someone can give a solution.

**Comment by TrueRhench** [comment]
I've also been using the bot and had the same issue.

I spoke to some people on the Showdown website and they told me that looking at the code, it's using insecure websockets.
https://github.com/pmariglia/showdown/blob/master/showdown/websocket_client.py#L34
&Hecate: Change this to wss:// and it'll be fine.

**Comment by singiamtel** [comment]
Yeah apparently doesn't support ws:// anymore. 

I can connect using wss:// and ``WEBSOCKET_URI=sim3.psim.us``

**Comment by pmariglia** [comment]
sorry I've been busy - thanks for opening this.

Should be fixed in 339732bed4c7af3aafa89bcc1ffc939cf08b81f8
