### ISSUE TITLE
Problem with starting up the bot

### ISSUE THREAD

**Issue by Canoli5** [pmariglia/showdown#196]
I tried to run the bot using both methods and both times it came back with this error:
File "C:\showdown\showdown\websocket_client.py", line 89, in login
    if not response_json['actionsuccess']:
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'actionsuccess'

I just want to preface that I have very little knowledge when it comes to coding so I'm sorry if this is an easy fix and I'm wasting your time. But if you know how to fix this or have an idea of how to fix it that would be amazing.

**Comment by link-discord** [comment]
This occurs when you enter the wrong password. Just had this myself but noticed I used the wrong username in my env file

**Comment by pmariglia** [comment]
Should have a better error message in 3878e1a7bc70b50bfbdea420f0a252303ffa0d3b
