### ISSUE TITLE
Closing Rooms

### ISSUE THREAD

**Issue by weIlThought** [pmariglia/showdown#204]
Maybe an option or config so the Bot closes the challenge room after the battle ends before opening a new one.

**Comment by pmariglia** [comment]
What is a challenge room? Do you mean the battle? The bot [leaves the room](https://github.com/pmariglia/showdown/blob/375ae499ce543d3c124bec53cbba67c74848dad8/showdown/websocket_client.py#L150) after the battle already.

Or are you talking about [this room](https://github.com/pmariglia/showdown/blob/375ae499ce543d3c124bec53cbba67c74848dad8/showdown/websocket_client.py#L39) that can be optionally joined ?

**Comment by weIlThought** [comment]
Yea the Battle; If i use /leave manually it works.
But while using the Bot, nothing happens.. The battle ends and a new one gets searched and started while leaving the other battle open aside.

**Comment by pmariglia** [comment]
Are you also logged into the account on your browser while this is happening?

I've noticed myself that `/leave` only instructs the _bot_ to leave the room, not every client logged-into that account. If the bot is the only client logged-info the account then it definitely leaves the battle afterwards.

I am not aware of any P.S. command that makes every connected client logged-into that account leave the room. [P.S. PROTOCOL reference](https://github.com/smogon/pokemon-showdown/blob/master/PROTOCOL.md)

**Comment by weIlThought** [comment]
Ahh, yes i have also the Browser open while using the bot.
