### ISSUE TITLE
I cant find any .env file

### ISSUE THREAD

**Issue by KiwiPowerGreen** [pmariglia/showdown#31]
I cant find any .env file in the files.

**Comment by pmariglia** [comment]
Hi.

The `.env` file is configuration and is not supplied in the code. You must create your own.

From the README:

Here is a minimal .env file. This configuration will log in and search for a gen8randombattle:
```WEBSOCKET_URI=sim.smogon.com:8000
PS_USERNAME=MyCoolUsername
PS_PASSWORD=MySuperSecretPassword
BOT_MODE=SEARCH_LADDER
POKEMON_MODE=gen8randombattle
RUN_COUNT=1```


You must supply your own username/password combination.

**Comment by pmariglia** [comment]
Closing as this is a non-issue
