### ISSUE TITLE
Any public ranking available for all known battle bots?

### ISSUE THREAD

**Issue by arochettesteinberg** [pmariglia/showdown#32]
Hi,

just heard for the first time about Pokemon showdown and initiatives similar like yours to develop an almighty battle bot: the one that'll defeat 'em all!
Are you guys gathering every known bot's performance into a single Top Bots Elo Ranking board by any chance? I can't get an overview of all the past and ongoing bots and how they eventually perform against real players.

Thanks!

**Comment by pmariglia** [comment]
Hello 👋 

>Are you guys gathering every known bot's performance into a single Top Bots Elo Ranking board by any chance?

Are you referring to the bots in the repository? I have tested the `safest` and the `nash_equilibrium` bots against the OU ladder for thousands of games each - the result is that the `safest` performs the best, with an average of ~1450 ELO right now. There are some nuances, for example the team being used will affect how well the bot performs.

I do not maintain a board that tracks the performance of each bot, but it is an interesting idea!

Or were you referring to work done by other people? I have looked at a few:
- https://github.com/Synedh/showdown-battle-bot
- https://github.com/vasumv/pokemon_ai
- https://bitbucket.org/davidstone/technical-machine/src/master/
- https://github.com/yuzeh/metagrok

I am not familiar with the performance of these bots on the ladder, you would have to ask the authors. Most of these other bots seems to be discontinued though and may not work with Gen8.

There is also a project you might find interesting that creates a Pokemon AI battle-arena . I am not sure if this has been discontinued either:
- https://github.com/dramamine/leftovers-again

**Comment by arochettesteinberg** [comment]
Thanks for the quick reply and the links!
Yes I am referring to a world ranking board for all the battle bots, likey they do for chess engines for instance. Might be interesting to make competitions too!

**Comment by pmariglia** [comment]
I'm going to close this as it is not something I see being apart of this project.

Thanks again for your question.
