### ISSUE TITLE
challenge user mode not working?

### ISSUE THREAD

**Issue by fleetwoodmac** [pmariglia/showdown#39]
Trying to set up two bots to fight each other in gen8ou to get data for move accuracy.

Have each bot running in their own docker instance on two separate VMs. Confirmed that the bots work fine in ladder mode and accept_challenge mode. But neither can send challenges

Cases I tried:
1. Sending challenge to human account (none received)
2. sending challenge to another bot (not received)
3. separate IPs for bot and human account (not received)
4. same IPs for bot and human (not received)
5. changing game mode to gen8randombattle for each of the above cases
6. removing "Team_Name" line and trying above cases

Here is the ENV file I have set up
![image](https://user-images.githubusercontent.com/69140036/89157445-64342f00-d521-11ea-9e03-a3dbc406b66c.png)

**Comment by pmariglia** [comment]
That's odd. Just tried and CHALLENGE_USER definitely works. Here is the config I used.
```
BATTLE_BOT=safest
WEBSOCKET_URI=sim.smogon.com:8000
PS_USERNAME=NiceNameNerd
PS_PASSWORD=<redacted>
BOT_MODE=CHALLENGE_USER
USER_TO_CHALLENGE=Accelerock Ttar
POKEMON_MODE=gen8randombattle
RUN_COUNT=1
```

The only thing I'd think it could be is:
1. The password is incorrect (I just noticed that even if the password is deliberately mistyped the log still says "Successfully logged in" - I'm going to fix that.
2. The USER_TO_CHALLENGE is incorrect

**Comment by pmariglia** [comment]
9db58db makes it so that an incorrect username/password triggers an error.

Doesn't explain why you're having trouble though..

**Comment by jubjubinspace** [comment]
Search Ladder and accept challenge work without changing the user/pass combo, so I definitely have the right password set,

user to challenge is set to the correct username

still not working unfortunately

**Comment by pmariglia** [comment]
I re-added some logging for the websocket messages that I removed once upon a time. This is in 0b38325.

If you still have trouble, could you pull the latest code and post what the `CHALLENGE_USER` bot's logs say?

The logs shouldn't have any passwords but if you want to remove usernames then give it a glance before pasting it.

**Comment by jubjubinspace** [comment]
Update: Problem seems to be on my end as per the websocket logs:
![image](https://user-images.githubusercontent.com/69140036/89245095-efaece00-d5bc-11ea-8d70-0a1d393cb136.png)


Thank you for enabling extra logs and helping me get to the bottom of this!

**Comment by jubjubinspace** [comment]
Hey so I've fixed a bunch of errors I had on my end, but now I'm getting a new error:

Situation:
Bots set up in a gen8anythinggoes match, valid teams, battle initiates but then I get this error:

![image](https://user-images.githubusercontent.com/69140036/89281132-7afc8380-d5fe-11ea-8788-1e676d0e44c1.png)

any idea of what i'm doing wrong now?

**Comment by pmariglia** [comment]
Another dumb oversight by me.

For niche tiers like anythinggoes there aren't always moveset files on [the smogon stats pages](https://www.smogon.com/stats/2020-07/moveset/), so in the past (during gen7) I hard-coded the bot to get information from all of the tiers if the bot plays a game where the file does not exist. Now that gen7 is over `gen7ru` doesn't exist anymore so the bot is erroring when trying to read the sets from that file.

The bot needs this information to make assumptions about what moves/spreads/items/abilities the opponent's pokemon could have.

I changed the hard-coded tiers to their gen8 counterparts in 9cd7590bbddf7e so you should be OK now.

**Comment by pmariglia** [comment]
Going to assume the silence means your problem has been resolved.

Feel free to reopen if it is not.
