### ISSUE TITLE
Get the adversary team

### ISSUE THREAD

**Issue by Andyloris** [pmariglia/showdown#48]
Is there any ways to get the adversary team ?

Thanks in advance

**Comment by hsahovic** [comment]
Hi @Andyloris,

If I understand your question correctly, the answer is yes: you can access [`battle.opponent_team`](https://poke-env.readthedocs.io/en/stable/battle.html#poke_env.environment.abstract_battle.AbstractBattle.opponent_team), which is a dictionary whose values are `Pokemon` objects representing the opponent's team.

**Comment by Andyloris** [comment]
ok thanks !

**Comment by hsahovic** [comment]
@Andyloris I just realized that I mistakenly responded to this issue, thinking it was opened in another similar repo - sorry about that, I didn't pay sufficient attention to the notification.

I think that you can use `battle.opponent.reserve` which should be a list quite similar to what I described above, but you'd want @pmariglia to confirm that.

**Comment by pmariglia** [comment]
Hi, sorry I just saw this now.

@hsahovic is correct that if you are interfacing with the `battle` object then the opponent's team is `battle.opponent.reserve`. If you are interfacing with the state object, then similarly it is `state.opponent.reserve`. (the state is part of the engine, and separate from the `battle` that is used to track the showdown battle)

If you need further clarification please feel free to re-open this and ask, thanks.
