### ISSUE TITLE
[Feature Request] Have bot join chatroom to enable easy challenging.

### ISSUE THREAD

**Issue by iWiggins** [pmariglia/showdown#49]
It would be beneficial if a "chatroom" variable or similar could be specified to allow the bot to join a chatroom. That way, users could send challenges to it without needing to look up its name.

**Comment by pmariglia** [comment]
An excellent request.

19dd5485155e66732981a0081257c0d8cf1ad5c5 adds this feature if the bot is run in `ACCEPT_CHALLENGE` mode. 

Side effect is that the logs are a bit cluttered with the chatroom's messages - but the logging level can be changed to INFO if that is too annoying.

**Comment by pmariglia** [comment]
Closing this as the feature was added - if you experience any problems with it please feel free to re-open.
