### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u2606'

### ISSUE THREAD

**Issue by rahidz** [pmariglia/showdown#52]
Error shows up at the end of each battle when logging is enabled, presumably it's trying to encode the star character (☆) before the username and is failing to do so.

**Comment by pmariglia** [comment]
I need a bit more information as I cannot reproduce, is this an error that stops the bot or just a problem printing to the console?

Could you provide the log output please, preferrably a bit leading up to the error as well.

Also how are you running the bot when this happens? Via Docker or locally? If local, which Python version are you using?

**Comment by rahidz** [comment]
I can't replicate it either any more. I think it was happening on both Docker and locally but not sure. Since I can't repro it I'mma close it.
