### ISSUE TITLE
problem with nash-equilibrium mode

### ISSUE THREAD

**Issue by ShadowPeregrine** [pmariglia/showdown#54]
under showdown in the **battlebots** folder, **nash-equilibrium** is not working for me. Apparently the problem is in main.py(in the nash-equilibrium folder) caused by the line
"**from nashpy import Game**" in line 8 _but_ nashpy doesn't exist.
Thankyou.

**Comment by pmariglia** [comment]
This could be a couple things:

[Nashpy is a requirement defined in the requirements.txt file](https://github.com/pmariglia/showdown/blob/294bf4990d29ecd87d310a47f68afa21eb873c75/requirements.txt#L5). Are you installing the requirements properly?

Also, are you running locally, or with Docker? You should only run that battle mode when using Docker.

From the README: 

```
The Nash Equilibrium is calculated using command-line tools provided by the Gambit project.

This decision method should only be used when running with Docker and will fail otherwise.
```

**Comment by ShadowPeregrine** [comment]
@pmariglia hey! it worked when i try to install nashpy by itself instead of doing "python -m pip install -r requirements.txt". i don't know why it didn't install when i originally tried to run the install command. Thankyou
