### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by ShadowPeregrine** [pmariglia/showdown#55]
here are a few suggestions from my experience of this script:
1. make nash-equilibrium run without docker. the docker took like 2 gb so making it run without docker would be appreciated.
2. it doesn't switch pokemon. when its a in a sticky situation in a fight, it doesn't switch pokemon making the pokemon die.
3. making it a neural network for extra intelligence???
4. add a stall feature. I noticed when the bot was being slow due to other applications, the timer would be on and people would leave if no move would be done increasing my elo a lot.
Overall the bot is amazing ,very fast and works very well.
Thanks in advance

**Comment by pmariglia** [comment]
1. Running without Docker requires the user to set up their own Gambit binaries - it's more of a headache to do that than to run Docker. Yeah the Docker image is based on an ubuntu image ([reference](https://github.com/pmariglia/gambit-docker/blob/68e53b7e1a9d7ea671d77e61a2c6262867eb0529/Dockerfile#L1)) - the image size could probably be brought down by using something like Debian-slim, but not by too much. I can make that change when I get the chance but if you want to run without Docker you'll need to compile the [Gambit ](https://github.com/gambit/gambit)binaries on your own machine, and then use [this environment variable ](https://github.com/pmariglia/showdown/blob/294bf4990d29ecd87d310a47f68afa21eb873c75/Dockerfile#L19) to point to the `gambit-enummixed` binary.

2. At all? If it isn't considering switches then that is a bug, but you'll have to provide more context/evidence. The bot isn't perfect - far from it and I never claimed it was. Or does it just not switch in situations where you think it should switch? The decisions are just based off of the algorithm being used.

3. I do not have the background knowledge nor the interest in doing this right now.

4. Lol?

**Comment by ShadowPeregrine** [comment]
yea i am also serious about the 4th one lmao

**Comment by merkrafter** [comment]
1. Are you on Windows? On my machine, the Docker image "only" takes 1.3 GB. Anyway, I created a PR (#57 ) that saves ~600MB by utilizing multi-staged docker build. Maybe this is enough for your use case to profit from docker.

**Comment by pmariglia** [comment]
Closed as none of the items are really addressable.

@merkrafter helped with this comment: ae34aa85ca0766a88b25e663d2e8735ad9094bfc which reduces the size of the docker image to just under 400MB (on my machine anyways).
