### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by ShadowPeregrine** [pmariglia/showdown#56]
I know i have been annoying with all these issues but i am curious to know, how all of this works. I have gone through the code for 2 hours straight but i couldn't understand much, especially how it retrieves the data and executes the moves.
Can you point me to any tutorials or explain it yourself?
Discord if you want to message me there:  ☙ Surya ❧#8330
Thankyou

**Comment by ShadowPeregrine** [comment]
Also i am planning to add reinforcement to it as i have quite a lot of experience with reinforcement.

**Comment by pmariglia** [comment]
Feel free to send me a message on discord if you have any **specific** questions about the bot.

pmariglia#5568
