### ISSUE TITLE
How did you guys did this?

### ISSUE THREAD

**Issue by Squape** [pmariglia/showdown#67]
I'm building something similar but don't know where to get starteted. Can you tell me about how did you do this, no code, just an explanation

**Comment by Squape** [comment]
*started

**Comment by yoursred** [comment]
It uses MiniMax, a tree searching algorithm.

**Comment by pmariglia** [comment]
Yeah this project is an expectiminimax algorithm with a scoring function.

There's more to it of course - there's logic around keeping track of the state, determining the most likely moves/item/ability/spread that a Pokemon may have, interacting with the showdown server.

**Comment by Squape** [comment]
Thanks 👍‍‍
