### ISSUE TITLE
doesn't handle ties

### ISSUE THREAD

**Issue by Akkete** [pmariglia/showdown#70]
If a battle ends in a tie, the bot doesn't start a new battle. I encountered this when making two bots battle each other with stally teams and they triggered the endless battle clause.

**Comment by pmariglia** [comment]
Thnx for bringing this up. Fixed in 65befcbb49dfe33170adb989bdfd30167fa1fff5

**Comment by pmariglia** [comment]
Closing. Let me know if there are any problems.
