### ISSUE TITLE
tries to load .DS_Store as a team (macOS problem)

### ISSUE THREAD

**Issue by Akkete** [pmariglia/showdown#71]
MacOS creates a hidden `.DS_Store` file in most folders that are opened. When choosing teams from a folder the bot sometimes crashes because it tries to read the `.DS_Store` file as a team.

It would probably make sense to make the team selector ignore hidden files.

Meanwhile, I just avoid opening the team folders in Finder, so `.DS_Store` does not get created.

**Comment by pmariglia** [comment]
Hidden files ignored in 72eee9a668cd3724f4123b104a0709bea342ed9e.

Thanks for bringing this up! :slightly_smiling_face:
