### ISSUE TITLE
Probably just me being dumb but...

### ISSUE THREAD

**Issue by hypersonicstormm** [pmariglia/showdown#74]
Basically I was trying to get the bot working using Heroku and it went well until after I deployed it and went into the "Resources" tab. There I clicked on the "Open App" button and I see this (I'm assuming I clicked the wrong thing lol)
![image](https://user-images.githubusercontent.com/87400978/125545120-3be6863a-e230-4f30-9558-dd01e394ee3c.png)

(hope the image works... it just shows a link for me)

Did something go wrong or was I just dumb?

**Comment by pmariglia** [comment]
From the README:

```After deploying, go to the Resources tab and turn on the worker.```

The bot is basically a cli script, not a web application. Clicking "Open app" in heroku opens the heroku url, something like `showdownapp.herokuapp.com`. You want to use a worker to run the bot. Careful though, the bot will run indefinitely (restart itself once it terminates), potentially costing you money.

You can check the logs to verify it is running.

**Comment by pmariglia** [comment]
Closing this - let me know if you have any other questions.
