### ISSUE TITLE
Free for all

### ISSUE THREAD

**Issue by link-discord** [pmariglia/showdown#75]
Add Support for free for all battles. I think it might kind of difficult to track all pokemon though but u could make it try to predict what pokemon attacks which and make act accordingly there might also be other challenges though

**Comment by pmariglia** [comment]
I don't see myself getting to this.

The state representation, the battle engine, and the search algorithm are all written for 1v1 single battles.

I'm happy to accept PRs that contribute this, but it would be way too much work for me and I don't have any interest in it.

**Comment by pmariglia** [comment]
Closing this. Let me know if you have any other questions.
